package io.unityfoundation.dds.permissions.manager;

public enum ErrorCodes {
    // generic
    UNAUTHORIZED,

    // user
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,

    // group
    GROUP_NOT_FOUND,
    GROUP_ALREADY_EXISTS,
    GROUP_NAME_CANNOT_BE_BLANK_OR_NULL,

    // application
    APPLICATION_NOT_FOUND,
    APPLICATION_REQUIRES_GROUP_ASSOCIATION,
    APPLICATION_CANNOT_UPDATE_GROUP_ASSOCIATION,
    APPLICATION_ALREADY_EXISTS,
    APPLICATION_NAME_CANNOT_BE_BLANK_OR_NULL,
    IDENTITY_CERT_NOT_FOUND,
    PERMISSIONS_CERT_NOT_FOUND,
    GOVERNANCE_FILE_NOT_FOUND,

    // topic
    TOPIC_NOT_FOUND,
    TOPIC_UPDATE_NOT_ALLOWED,
    TOPIC_REQUIRES_GROUP_ASSOCIATION,
    TOPIC_NAME_CANNOT_BE_BLANK_OR_NULL,
    TOPIC_ALREADY_EXISTS,

    // group member
    USER_IS_VALID,
    USER_IS_NOT_VALID,
    GROUP_MEMBER_NOT_FOUND,

    // application permission
    APPLICATION_PERMISSION_NOT_FOUND
}
